import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { PrismaClient } from "@prisma/client";
import { Adapter } from "next-auth/adapters";
import { prisma } from "~/server/prisma";




const createUser = (data: any) => ({
    ...data,
    id: undefined,  //this forces a random id to be generated by the PrismaClient instead of using the id from the provider
});




export const customPrismaAdapter = (prisma: PrismaClient): Adapter => {
    const prismaAdapter = PrismaAdapter(prisma);

    return {
        ...prismaAdapter,
        createUser, //overwrite the createUser function
    };
};